### ISSUE TITLE
Errors when running npm run serve-js & npm run serve

### ISSUE THREAD

**Issue by caseyyee** [ngokevin/aframe-react-boilerplate#8]
npm run serve-js & npm run serve
[2] 14344

> aframe-react-boilerplate@1.0.0 serve-js /Users/casey/Developer/aframe-react-boilerplate
> webpack-dev-server --content-base src --progress --watch --history-api-fallback --inline --hot

> aframe-react-boilerplate@1.0.0 serve /Users/casey/Developer/aframe-react-boilerplate
> cd src && python -m SimpleHTTPServer 5555

Serving HTTP on 0.0.0.0 port 5555 ...
 70% 1/1 build modulesevents.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at net.js:1376:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)

npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/casey/.nvm/versions/node/v4.1.1/bin/node" "/Users/casey/.nvm/versions/node/v4.1.1/bin/npm" "run" "serve-js"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! aframe-react-boilerplate@1.0.0 serve-js: `webpack-dev-server --content-base src --progress --watch --history-api-fallback --inline --hot`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aframe-react-boilerplate@1.0.0 serve-js script 'webpack-dev-server --content-base src --progress --watch --history-api-fallback --inline --hot'.
npm ERR! This is most likely a problem with the aframe-react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --content-base src --progress --watch --history-api-fallback --inline --hot
npm ERR! You can get their info via:
npm ERR!     npm owner ls aframe-react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/casey/Developer/aframe-react-boilerplate/npm-debug.log
[2]  + 14344 exit 1     npm run serve-js
127.0.0.1 - - [11/Jan/2016 12:56:11] "GET / HTTP/1.1" 200 -
^CTraceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SimpleHTTPServer.py", line 235, in <module>
    test()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SimpleHTTPServer.py", line 231, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 599, in test
    httpd.serve_forever()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 236, in serve_forever
    poll_interval)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 155, in _eintr_retry
    return func(*args)
KeyboardInterrupt

Console:
![image](https://cloud.githubusercontent.com/assets/1560884/12246364/f654abb6-b862-11e5-8d42-0c61b2cfddcb.png)

**Comment by ngokevin** [comment]
Thanks, fixing this ASAP.

**Comment by ngokevin** [comment]
Weird, never had this issue before and didn't upgrade Babel or anything.

Fixed, thanks!
